### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by popiano123** [wjp-letgo/letgo-proxy#1]
package command-line-arguments
        imports github.com/Trisia/gosysproxy: build constraints exclude all Go files in /root/go/src/github.com/Trisia/gosysproxy

**Comment by wjp-letgo** [comment]
> package command-line-arguments imports github.com/Trisia/gosysproxy: build constraints exclude all Go files in /root/go/src/github.com/Trisia/gosysproxy

Need to install the "github. com/Trisia/gosysproxy" package
